package hello.controller;

import hello.service.QuestionsService;
import net.sf.json.JSONObject;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller    // This means that this class is a controller
@RequestMapping // This means URL's start with /demo (after Application path)
public class QuestionsController {

    // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data

    private final QuestionsService questionsService;

    @Autowired
    public QuestionsController(QuestionsService questionsService) {
        this.questionsService = questionsService;
    }

    @ResponseBody
    @PostMapping(path = "/getQuestionsByThemeId")
    public JSONObject getQuestionsByThemeId(Long themeId) {
        return questionsService.getQuestionsByThemeId(themeId);
    }

}
